alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi

grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false